local M ={}

M.groups = {
    ["@lsp.mod.declaration"] = "#{ bold = true }",
    ["@lsp.mod.definition"] = "#{ bold = true }",
    ["@lsp.mod.documentation"] = "Documentation",
    ["@lsp.mod.readonly"] = "Constant",
    ["@lsp.type.class"] = "Variable",
    ["@lsp.type.comment"] = "Comment",
    ["@lsp.type.decorator"] = "Attribute",
    ["@lsp.type.enum"] = "Enum",
    ["@lsp.type.enumMember"] = "Enum",
    ["@lsp.typemod.enumMember"] = "Enum",
    ["@lsp.type.function"] = "Function",
    ["@lsp.type.keyword"] = "Keyword",
    ["@lsp.type.macro"] = "Preprocessor",
    ["@lsp.type.method"] = "Function",
    ["@lsp.type.modifier"] = "Attribute",
    ["@lsp.type.namespace"] = "#{ bold = true }",
    ["@lsp.type.number"] = "Number",
    ["@lsp.type.operator"] = "Operator",
    ["@lsp.type.property"] = "Attribute",
    ["@lsp.type.regexp"] = "Regex",
    ["@lsp.type.string"] = "String",
    ["@lsp.type.typeParameter"] = "Variable",
    ["@lsp.type.variable"] = "Variable",
    ["Boolean"] = "Boolean",
    ["Character"] = "Char",
    ["Comment"] = "Comment",
    ["Conditional"] = "ControlFlow",
    ["Constant"] = "Constant",
    ["Define"] = "Preprocessor",
    ["Delimiter"] = "Operator",
    ["Error"] = "Error",
    ["Exception"] = "ControlFlow",
    ["Float"] = "Float",
    ["Function"] = "Function",
    ["Identifier"] = "Normal",
    ["Include"] = "Preprocessor",
    ["Keyword"] = "Keyword",
    ["Label"] = "Variable",
    ["Macro"] = "Preprocessor",
    ["Number"] = "Number",
    ["Operator"] = "Operator",
    ["PreCondit"] = "Preprocessor",
    ["PreProc"] = "Preprocessor",
    ["Repeat"] = "ControlFlow",
    ["Special"] = "Char",
    ["SpecialChar"] = "Char",
    ["Statement"] = "ControlFlow",
    ["String"] = "String",
    ["Tag"] = "#{ bold = true }",
    ["Todo"] = "Information",
    ["Type"] = "DataType",
    ["Typedef"] = "Keyword",
    ["Underlined"] = "#{ underline = true }",
    ["@attribute"] = "Attribute",
    ["@attribute.builtin"] = "Attribute",
    ["@boolean"] = "Normal",
    ["@character"] = "Char",
    ["@character.special"] = "SpecialChar",
    ["@comment"] = "Comment",
    ["@comment.documentation"] = "Documentation",
    ["@comment.error"] = "Error",
    ["@comment.note"] = "Information",
    ["@comment.todo"] = "Information",
    ["@comment.warning"] = "Warning",
    ["@constant"] = "Constant",
    ["@constant.builtin"] = "Constant",
    ["@constant.macro"] = "Preprocessor",
    ["@constructor"] = "Function",
    ["@constructor.lua"] = "Operator",
    ["@function"] = "Function",
    ["@function.builtin"] = "BuiltIn",
    ["@function.call"] = "Function",
    ["@function.macro"] = "Preprocessor",
    ["@function.method"] = "Function",
    ["@function.method.call"] = "Function",
    ["@keyword"] = "Keyword",
    ["@keyword.conditional"] = "ControlFlow",
    ["@keyword.conditional.ternary"] = "Operator",
    ["@keyword.coroutine"] = "ControlFlow",
    ["@keyword.debug"] = "ControlFlow",
    ["@keyword.directive"] = "Comment",
    ["@keyword.directive.c"] = "Preprocessor",
    ["@keyword.directive.cpp"] = "Preprocessor",
    ["@keyword.directive.define"] = "Preprocessor",
    ["@keyword.exception"] = "ControlFlow",
    ["@keyword.function"] = "Keyword",
    ["@keyword.import"] = "Import",
    ["@keyword.modifier"] = "Keyword",
    ["@keyword.operator"] = "Keyword",
    ["@keyword.repeat"] = "ControlFlow",
    ["@keyword.return"] = "ControlFlow",
    ["@keyword.type"] = "Keyword",
    ["@label"] = "Variable",
    ["@markup.heading"] = "MarkHead",
    ["@markup.heading.1"] = "MarkHead",
    ["@markup.heading.2"] = "MarkHead",
    ["@markup.heading.3"] = "MarkHead",
    ["@markup.heading.4"] = "MarkHead",
    ["@markup.heading.5"] = "MarkHead",
    ["@markup.heading.6"] = "MarkHead",
    ["@markup.italic"] = "#{ italic = true }",
    ["@markup.link"] = "MarkLink",
    ["@markup.link.label"] = "MarkLinkLabel",
    ["@markup.link.markdown_inline"] = "MarkLinkInline",
    ["@markup.math"] = "Normal",
    ["@markup.quote"] = "MarkQuote",
    ["@markup.raw.block"] = "MarkCode",
    ["@markup.raw.markdown_inline"] = "MarkCode",
    ["@markup.raw"] = "MarkCode",
    ["@markup.strikethrough"] = "#{ strikethrough = true }",
    ["@markup.strong"] = "#{ bold = true }",
    ["@markup.underline"] = "#{ underline = true }",
    ["@module"] = "Normal",
    ["@module.builtin"] = "Normal",
    ["@number"] = "Number",
    ["@number.float"] = "Float",
    ["@operator"] = "Operator",
    ["@property"] = "Attribute",
    ["@punctuation.bracket"] = "Operator",
    ["@punctuation.delimiter"] = "Operator",
    ["@punctuation.special"] = "Operator",
    ["@string"] = "String",
    ["@string.documentation"] = "Documentation",
    ["@string.escape"] = "Char",
    ["@string.regexp"] = "Regex",
    ["@string.special"] = "SpecialString",
    ["@string.special.path"] = "String",
    ["@string.special.symbol"] = "Variable",
    ["@string.special.url"] = "MarkLink",
    ["@tag"] = "#{ bold = true }",
    ["@tag.attribute"] = "TagAttribute",
    ["@tag.delimiter"] = "TagDelimiter",
    ["@type"] = "DataType",
    ["@type.builtin"] = "DataType",
    ["@type.definition"] = "Keyword",
    ["@variable"] = "Variable",
    ["@variable.builtin"] = "Variable",
    ["@variable.member"] = "Normal",
    ["@variable.parameter"] = "Variable",
    ["@variable.parameter.builtin"] = "Variable",
}

M.setup = function()
    return M.groups
end

return M