local M = {}

M.groups = {
    ["ColorColumn"] = { bg = "#232629" },
    ["ComplHint"] = {  },
    ["ComplHintMore"] = {  },
    ["ComplMatchIns"] = {  },
    ["Conceal"] = {  },
    ["CurSearch"] = { link = "Visual" },
    ["Cursor"] = { fg = "bg", bg = "fg" },
    ["CursorColumn"] = { bg = "#2a2e32" },
    ["CursorIM"] = { link = "" },
    ["CursorLine"] = { bg = "#2a2e32" },
    ["CursorLineFold"] = { link = "FoldColumn" },
    ["CursorLineNr"] = { fg = "#a5a6a8", bg = "#2e2e32" },
    ["CursorLineSign"] = { bg = "#2e2e32" },
    ["DiffAdd"] = { fg = "#1c8042" },
    ["DiffChange"] = { fg = "#c04900" },
    ["DiffDelete"] = { fg = "#da4453" },
    ["DiffText"] = { link = "DiffChange" },
    ["DiffTextAdd"] = { link = "DiffChange" },
    ["Directory"] = { fg = "#1d99f3", bold = true },
    ["EndOfBuffer"] = {  },
    ["ErrorMsg"] = { fg = "#da4453" },
    ["FloatBorder"] = {  },
    ["FloatFooter"] = {  },
    ["FloatShadow"] = {  },
    ["FloatShadowThrough"] = {  },
    ["FloatTitle"] = {  },
    ["FoldColumn"] = { bg = "#224e65" },
    ["Folded"] = { underdashed = true, sp = "#224e65" },
    ["IncSearch"] = { link = "Visual" },
    ["LineNr"] = { fg = "#7a7c7d", bg = "#31363b" },
    ["LineNrAbove"] = { link = "LineNr"  },
    ["LineNrBelow"] = { link = "LineNr" },
    ["MatchParen"] = { bg = "#000000" },
    ["ModeMsg"] = { fg = "#11d116" },
    ["MoreMsg"] = { fg = "#1d99f3" },
    ["MsgArea"] = {  },
    ["MsgSeparator"] = {  },
    ["NonText"] = {  },
    ["Normal"] = { fg = "#cfcfc2", bg = "#232629" },
    ["NormalFloat"] = { link = "Normal" },
    ["NormalNC"] = { link = "Normal" },
    ["OkMsg"] = { fg = "#1c8042" },
    ["Pmenu"] = {  },
    ["PmenuBorder"] = {  },
    ["PmenuExtra"] = {  },
    ["PmenuExtraSel"] = {  },
    ["PmenuKind"] = {  },
    ["PmenuKindSel"] = {  },
    ["PmenuMatch"] = {  },
    ["PmenuMatchSel"] = {  },
    ["PmenuSbar"] = {  },
    ["PmenuSel"] = {  },
    ["PmenuShadow"] = {  },
    ["PmenuShadowThrough"] = {  },
    ["PmenuThumb"] = {  },
    ["PreInsert"] = {  },
    ["Question"] = { fg = "#1d99f3" },
    ["QuickFixLine"] = { fg = "#1d99f3" },
    ["Search"] = { fg = "#cfcfc2", bg = "#414857" },
    ["SignColumn"] = { bg = "#31363b" },
    ["SnippetTabstop"] = {  },
    ["SnippetTabstopActive"] = {  },
    ["SpecialKey"] = { fg = "#3daee9" },
    ["SpellBad"] = { undercurl = true, sp = "#da4453" },
    ["SpellCap"] = { undercurl = true, sp = "#f67e00" },
    ["SpellLocal"] = { undercurl = true, sp = "#1c8042" },
    ["SpellRare"] = { undercurl = true, sp = "#3daee9" },
    ["StatusLine"] = { fg = "#fcfcfc", bg = "#1b1d20" },
    ["StatusLineNC"] = { link = "StatusLine" },
    ["StatusLineTerm"] = { link = "StatusLine" },
    ["StatusLineTermNC"] = { link = "StatusLine" },
    ["StderrMsg"] = { link = "ErrorMsg"  },
    ["StdoutMsg"] = { fg = "#cfcfc2" },
    ["Substitute"] = { fg = "#cfcfc2", bg = "#808021" },
    ["TabLine"] = { link = "StatusLine" },
    ["TabLineFill"] = { link = "StatusLine" },
    ["TabLineSel"] = { fg = "#fcfcfc", bg = "#232629", underline = true, sp = "#3daee9" },
    ["TermCursor"] = { fg = "#232629", bg = "#cfcfc2" },
    ["Title"] = { bold =true },
    ["Visual"] = { fg = "#cfcfc2", bg = "#2d5c76" },
    ["VisualNOS"] = { link = "Visual" },
    ["WarningMsg"] = { fg = "#f67e00" },
    ["Whitespace"] = { fg = "#4d4d4d" },
    ["WildMenu"] = {  },
    ["WinBar"] = {  },
    ["WinBarNC"] = {  },
    ["WinSeparator"] = {  },
    ["lCursor"] = {  },
}

M.setup = function()
    return M.groups
end

return M
