#backup内为需要备份的内容，文件夹后的*需要保留，键为备份标识，空格需要带上转义字符
backup:
  mpv: "~/.config/mpv/*"
  mpd: "~/.config/mpd/*"
  ncmpcpp: "~/.config/ncmpcpp/*"
  fontconfig: "~/.config/fontconfig/*"
  pipewire: "~/.config/pipewire/*"
  wireplumber: "~/.config/wireplumber/*"
  rime:
    - "~/.local/share/fcitx5/rime/wanxiang.userdb"
    - "~/.local/share/fcitx5/rime/*.custom.yaml"
  pacman: "/etc/pacman.d/hooks/*"
  bash:
    - "~/.bashrc"
    - "~/.inputrc"
  Beiming\ C++\ Library: "~/Program/Beiming\\ C++\\ Library/*"
  tlp: "/etc/tlp.conf"
