// 关闭预加载
user_pref("network.prefetch-nextfalse", false);
// 中键粘贴
user_pref("middlemouse.paste", true);
// 允许最多弹出窗口
user_pref("dom.popup_maximum", 3);
// 关闭最后标签不退出
user_pref("browser.tabs.closeWindowWithLastTab", false);
// 去除受保护页面
user_pref("extensions.webextensions.restrictedDomains", '');
// 自定义样式
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
// 启用FFmpeg的VAAPI
user_pref("media.ffmpeg.vaapi.enabled", true);
// 使用系统文件选择器
user_pref("widget.use-xdg-desktop-portal.file-picker", 1);
// 禁止下载时连接Google进行安全校验
user_pref("browser.safebrowsing.downloads.enabled", false);
// 优先使用DoH
user_pref("network.trr.mode", 2);
// 禁止DNS预解析
user_pref("network.dns.disablePrefetch", 1);
user_pref("network.dns.disablePrefetchFromHTTPS", 1);
// 启用WebRender渲染器
user_pref("gfx.webrender.all", true);
// 强制使用硬件加速
user_pref("acceleration.force-enabled", true);
