stream.rules = [
    {
        matches = [
            {
                application.name = "Music Player Daemon"
                application.name = "mpv"
            }
        ]
        actions = {
            update-props = {
                node.lock-quantum = true
                node.exclusive = true
                stream.dont-remix = true
                resample.quality = 14
                resample.disable = true
                node.suspend-on-idle = false
                channelmix.disable = true
            }
        }
    }
]
