local M = {}

M.groups = {
    ["@attribute.cpp"] = {  },
    ["@boolean.cpp"] = {  },
    ["@character.cpp"] = {  },
    ["@comment.cpp"] = {  },
    ["@comment.documentation.cpp"] = {  },
    ["@constant.cpp"] = {  },
    ["@constant.builtin.cpp"] = {  },
    ["@constant.macro.cpp"] = {  },
    ["@constructor.cpp"] = {  },
    ["@function.cpp"] = {  },
    ["@function.builtin.cpp"] = {  },
    ["@function.call.cpp"] = {  },
    ["@function.macro.cpp"] = {  },
    ["@function.method.cpp"] = {  },
    ["@function.method.call.cpp"] = {  },
    ["@keyword.cpp"] = {  },
    ["@keyword.conditional.cpp"] = {  },
    ["@keyword.conditional.ternary.cpp"] = {  },
    ["@keyword.coroutine.cpp"] = {  },
    ["@keyword.directive.cpp"] = {  },
    ["@keyword.directive.define.cpp"] = {  },
    ["@keyword.exception.cpp"] = {  },
    ["@keyword.import.cpp"] = {  },
    ["@keyword.modifier.cpp"] = {  },
    ["@keyword.operator.cpp"] = {  },
    ["@keyword.repeat.cpp"] = {  },
    ["@keyword.return.cpp"] = {  },
    ["@keyword.type.cpp"] = {  },
    ["@label.cpp"] = {  },
    ["@module.cpp"] = {  },
    ["@number.cpp"] = {  },
    ["@operator.cpp"] = {  },
    ["@property.cpp"] = {  },
    ["@punctuation.bracket.cpp"] = {  },
    ["@punctuation.delimiter.cpp"] = {  },
    ["@punctuation.special.cpp"] = {  },
    ["@spell.cpp"] = {  },
    ["@string.cpp"] = {  },
    ["@string.escape.cpp"] = {  },
    ["@type.cpp"] = {  },
    ["@type.builtin.cpp"] = {  },
    ["@type.definition.cpp"] = {  },
    ["@variable.cpp"] = {  },
    ["@variable.builtin.cpp"] = {  },
    ["@variable.member.cpp"] = {  },
    ["@variable.parameter.cpp"] = {  },
}

M.setup = function()
    return M.groups
end

return M