local M = {}

M.groups = {
    ["@attribute.javascript"] = {  },
    ["@boolean.javascript"] = {  },
    ["@character.special.javascript"] = {  },
    ["@comment.javascript"] = {  },
    ["@comment.documentation.javascript"] = {  },
    ["@constant.javascript"] = {  },
    ["@constant.builtin.javascript"] = {  },
    ["@constructor.javascript"] = {  },
    ["@function.javascript"] = {  },
    ["@function.builtin.javascript"] = {  },
    ["@function.call.javascript"] = {  },
    ["@function.method.javascript"] = {  },
    ["@function.method.call.javascript"] = {  },
    ["@keyword.javascript"] = {  },
    ["@keyword.conditional.javascript"] = {  },
    ["@keyword.conditional.ternary.javascript"] = {  },
    ["@keyword.coroutine.javascript"] = {  },
    ["@keyword.directive.javascript"] = {  },
    ["@keyword.exception.javascript"] = {  },
    ["@keyword.function.javascript"] = {  },
    ["@keyword.import.javascript"] = {  },
    ["@keyword.operator.javascript"] = {  },
    ["@keyword.repeat.javascript"] = {  },
    ["@keyword.return.javascript"] = {  },
    ["@keyword.type.javascript"] = {  },
    ["@label.javascript"] = {  },
    ["@markup.heading.javascript"] = {  },
    ["@markup.heading.1.javascript"] = {  },
    ["@markup.heading.2.javascript"] = {  },
    ["@markup.heading.3.javascript"] = {  },
    ["@markup.heading.4.javascript"] = {  },
    ["@markup.heading.5.javascript"] = {  },
    ["@markup.heading.6.javascript"] = {  },
    ["@markup.italic.javascript"] = {  },
    ["@markup.link.label.javascript"] = {  },
    ["@markup.raw.javascript"] = {  },
    ["@markup.strikethrough.javascript"] = {  },
    ["@markup.strong.javascript"] = {  },
    ["@markup.underline.javascript"] = {  },
    ["@module.javascript"] = {  },
    ["@module.builtin.javascript"] = {  },
    ["@none.javascript"] = {  },
    ["@number.javascript"] = {  },
    ["@operator.javascript"] = {  },
    ["@punctuation.bracket.javascript"] = {  },
    ["@punctuation.delimiter.javascript"] = {  },
    ["@punctuation.special.javascript"] = {  },
    ["@spell.javascript"] = {  },
    ["@string.javascript"] = {  },
    ["@string.escape.javascript"] = {  },
    ["@string.regexp.javascript"] = {  },
    ["@string.special.url.javascript"] = {  },
    ["@tag.javascript"] = {  },
    ["@tag.attribute.javascript"] = {  },
    ["@tag.builtin.javascript"] = {  },
    ["@tag.delimiter.javascript"] = {  },
    ["@type.javascript"] = {  },
    ["@type.builtin.javascript"] = {  },
    ["@variable.javascript"] = {  },
    ["@variable.builtin.javascript"] = {  },
    ["@variable.member.javascript"] = {  },
    ["@variable.parameter.javascript"] = {  },
}

M.setup = function()
    return M.groups
end

return M