local M = {}

M.groups = {
    ["@attribute.python"] = {  },
    ["@attribute.builtin.python"] = {  },
    ["@boolean.python"] = {  },
    ["@character.special.python"] = {  },
    ["@comment.python"] = {  },
    ["@constant.python"] = {  },
    ["@constant.builtin.python"] = {  },
    ["@constructor.python"] = {  },
    ["@function.python"] = {  },
    ["@function.builtin.python"] = {  },
    ["@function.call.python"] = {  },
    ["@function.macro.python"] = {  },
    ["@function.method.python"] = {  },
    ["@function.method.call.python"] = {  },
    ["@keyword.python"] = {  },
    ["@keyword.conditional.python"] = {  },
    ["@keyword.coroutine.python"] = {  },
    ["@keyword.directive.python"] = {  },
    ["@keyword.exception.python"] = {  },
    ["@keyword.function.python"] = {  },
    ["@keyword.import.python"] = {  },
    ["@keyword.operator.python"] = {  },
    ["@keyword.repeat.python"] = {  },
    ["@keyword.return.python"] = {  },
    ["@keyword.type.python"] = {  },
    ["@module.python"] = {  },
    ["@module.builtin.python"] = {  },
    ["@none.python"] = {  },
    ["@nospell.python"] = {  },
    ["@number.python"] = {  },
    ["@number.float.python"] = {  },
    ["@operator.python"] = {  },
    ["@punctuation.bracket.python"] = {  },
    ["@punctuation.delimiter.python"] = {  },
    ["@punctuation.special.python"] = {  },
    ["@spell.python"] = {  },
    ["@string.python"] = {  },
    ["@string.documentation.python"] = {  },
    ["@string.escape.python"] = {  },
    ["@string.regexp.python"] = {  },
    ["@type.python"] = {  },
    ["@type.builtin.python"] = {  },
    ["@type.definition.python"] = {  },
    ["@variable.python"] = {  },
    ["@variable.builtin.python"] = {  },
    ["@variable.member.python"] = {  },
    ["@variable.parameter.python"] = {  },
}

M.setup = function()
    return M.groups
end

return M