context.properties={
  default.clock.rate          = 192000
  default.clock.allowed-rates = [ 44100 48000 96000 192000 ]
  default.clock.quantum       = 1024
  default.clock.min-quantum   = 512
  default.clock.max-quantum   = 2048
}
context.properties.rules=[
  {
    matches=[
      {
        node.name="~alsa_output.usb-EPZ_Technology_TP55.*"
      }
    ]
    actions={
      update-props={
        default.clock.rate          = 768000
        default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 352800 384000 705600 768000 ]
      }
    }
  }
]
