#参考/usr/share/doc/mpd/mpdconf.example与https://mpd.readthedocs.io/en/latest/mpd.conf.5.html
#音乐目录
music_directory       "~/Music"
#播放列表目录
playlist_directory    "~/.config/mpd/playlist"
#日志文件
log_file              "~/.config/mpd/mpd.log"
#日志等级
#log_level             "verbose"
#端口
port                  "6600"
#音乐数据库文件
db_file               "~/.config/mpd/music.db"
#歌词数据库文件
sticker_file          "~/.config/mpd/sticker.sql"
#自动更新音乐数据库
auto_update           "yes"
#常规输出设置
audio_output {
    type "pipewire"
    name "Default Pipewire"
    always_on "yes"
    mixer_type "none"
}
#ncmpcpp音频可视化
audio_output {
    type                    "fifo"
    name                    "ncmpcpp_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
