# 缓存目录
cache-dir = "~/.cache/ruff"
# 启用修复行为
fix = true
# 缩进数
indent-width = 4
# 行长限制
line-width = 120

[format]
# 格式化文档中的代码
docstring-code-format = true
# 缩进使用空格
indent-style = "space"
# 使用 Linux 行尾
line-ending = "lf"
# 尽量使用双引号
quote-style = "double"
# 尾随逗号
skip-magic-trailing-comma = true
