monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*MOONDROP_MOONRIVER_3*"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
