monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*TOPPING_DX1_II.*"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
