# Socket路径(留空自动配置)
socket=

# Thumbnail路径(留空自动配置)
thumbnail=

# thumbnail最大尺寸
max_height=200
max_width=200

# 缩放
scale_factor=1

# 应用色调映射
tone_mapping=auto

# Overlay id
overlay_id=42

# 文件加载时初始化缩略图，提高速度
spawn_first=yes

# 几秒后关闭缩略图处理程序，0禁用
quit_after_inactivity=0

# 网络播放禁用
network=no

# 音频播放禁用
audio=no

# 硬件解码启用
hwdec=yes

# Windows only: use native Windows API to write to pipe (requires LuaJIT)
direct_io=no

# Custom path to the mpv executable
mpv_path=mpv
