# 此文件定义 mpv 的快捷键绑定和 uosc 右键菜单项目

##=> uosc 一级菜单：常规
o  script-message-to uosc open-file            #menu: 常规 > 常规内置文件浏览器
i  script-binding stats/display-stats-toggle   #menu: 常规 > 统计信息
#  script-message-to uosc playlist             #menu: 常规 > 播放列表
#  script-message-to uosc chapters             #menu: 常规 > 章节
#  script-message-to uosc editions             #menu: 常规 > 版本
#  script-message-to uosc audio                #menu: 常规 > 音轨
#  script-message-to uosc subtitles            #menu: 常规 > 字幕

##=> uosc 一级菜单：截图
s        screenshot subtitles      #menu: 截图 > 有字幕
S        screenshot video          #menu: 截图 > 无字幕

##=> uosc 一级菜单：配置组
ALT+1    apply-profile 720P;show-text "配置组：720P 开"                 #menu: 配置组 > 720P 配置 > 开
ALT+2    apply-profile 720P restore;show-text "配置组：720P 关"         #menu: 配置组 > 720P 配置 > 关
ALT+3    apply-profile MutiSub;show-text "配置组：MutiSub 开"           #menu: 配置组 > MutiSub 配置 > 开
ALT+4    apply-profile MutiSub restore;show-text "配置组：MutiSub 关"   #menu: 配置组 > MutiSub 配置 > 关
ALT+5    apply-profile AlsaAudio;show-text "配置组：AlsaAudio 开"           #menu: 配置组 > AlsaAudio 配置 > 开
ALT+6    apply-profile AlsaAudio restore;show-text "配置组：AlsaAudio 关"   #menu: 配置组 > AlsaAudio 配置 > 关

##=> uosc 一级菜单
b        cycle window-minimized     #menu: 最小化
q        quit-watch-later           #menu: 退出并保存

##=> 以下键位不显示在 uosc 菜单中
MENU             script-message-to uosc menu-blurred    # 开/关 uosc 菜单
POWER            quit-watch-later                       # 退出并保存
PLAY             cycle pause;script-message-to uosc flash-pause-indicator    #播放指示
PAUSE            cycle pause;script-message-to uosc flash-pause-indicator    #暂停指示
PLAYPAUSE        cycle pause;script-message-to uosc flash-pause-indicator    #暂停指示
SPACE            cycle pause;script-message-to uosc flash-pause-indicator    #空格暂停
MBTN_RIGHT       script-message-to uosc menu-blurred    # 右键开/关 uosc 菜单
STOP             quit-watch-later      # 退出并保存
FORWARD          seek 30               # 快进
REWIND           seek -30              # 后退
RIGHT            seek 30               # 右快进
LEFT             seek -30              # 左后退
NEXT             playlist-next         # 下一个
PREV             playlist-prev         # 上一个
MBTN_LEFT_DBL    ignore
MBTN_RIGHT_DBL   ignore
MBTN_MID         ignore
MBTN_FORWARD     playlist-next;show-text "播放列表:${playlist-pos-1}/${playlist-count}" # 前进键 切换到列表中的下个文件
MBTN_BACK        playlist-prev;show-text "播放列表:${playlist-pos-1}/${playlist-count}" # 后退键 切换到列表中的上个文件
Wheel_Up         no-osd add volume  1; script-message-to uosc flash-volume   #增加音量
Wheel_Down       no-osd add volume -1; script-message-to uosc flash-volume   #减小音量
ESC              set fullscreen no;set window-maximized no                   #最小化
